# Generated by Django 5.0.6 on 2024-06-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('birth_day', models.DateField()),
                ('IIN', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('birth_day', models.DateField()),
                ('IIN', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('types', models.CharField(choices=[('C', 'Chocolade'), ('V', 'Vanila'), ('St', 'Strawberry')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk_Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outside_app.icecream')),
            ],
        ),
    ]
